# Change these first
owner: lehuygiang28 # Your GitHub organization or username, where this repository lives
repo: open-source-uptime # The name of this repository

sites:
  - name: Giaang Homepage
    url: https://giaang.id.vn
  - name: VNPay Lib Documentations
    url: https://vnpay-lib.vercel.app
  - name: '@vn-utils/text Documentations'
    url: https://vn-text.vercel.app
  - name: Github
    url: https://github.com/lehuygiang28
  - name: Uptime page
    url: https://uptime.giaang.id.vn
  - name: TechCell Api
    url: https://api.techcell.cloud/docs
  - name: TechCell FE
    url: https://techcell.cloud
  - name: TechCell Admin
    url: https://admin.techcell.cloud

assignees: # Users to assign downtime issues (optional)
  - lehuygiang28
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.giaang.id.vn
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "giaang's project uptime status page"
  introMessage: This is a status page which uses **real-time** data for my projects
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/lehuygiang28/open-source-uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
